// Tests for `trim attach` (cli/commands/attach.ts, cli/generators/attach-plan.ts,
// cli/project/trim-config-ast.ts, cli/project/control-uniqueness.ts,
// cli/project/resolve-typescript.ts, cli/prompts/attach-prompts.ts).
//
// Fixtures live INSIDE the repo tree (mkdtempSync under the repo root, like
// every other CLI test) so that generated files' self-references to the
// real built package resolve — NOT because attach needs a host
// `typescript`: it never touches one. It always parses with Trim's own
// bundled `@typescript/typescript6` (see cli/project/resolve-typescript.ts),
// so a host with no `typescript` installed at all still works fine — see
// the /tmp fixture below, kept outside the repo tree specifically so no
// `node_modules/typescript` is reachable via Node's resolution walk-up,
// proving the host's own TypeScript (or lack of it) is irrelevant.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

execFileSync('npm', ['run', 'build'], { cwd: root, stdio: 'pipe' });

const require = createRequire(import.meta.url);
const { serializeTrimMetadata } = require(path.join(root, 'dist/cli/project/trim-metadata.js'));
const { generateSettingsFileContents } = require(path.join(root, 'dist/cli/generators/settings-file.js'));
const { runAttachCommand } = require(path.join(root, 'dist/cli/commands/attach.js'));
const { gatherAttachInfo, buildAttachEdit } = require(path.join(root, 'dist/cli/generators/attach-plan.js'));
const { UsageError } = require(path.join(root, 'dist/cli/dispatch.js'));

const testRoot = mkdtempSync(path.join(root, '.trim-cli-attach-test-'));

const DEFAULT_CONFIG = `// Generated by Trim. Host-owned — customize freely; the Trim CLI only
// edits this file's \`groups\` array structurally, via \`trim attach\`.
import { defineTrimConfig } from "@theharborproject/trim/react";

export default defineTrimConfig({
  layout: "sections",
  groups: [],
});
`;

const NOOP_BOOLEAN_BINDING = '{ get: () => false, set: () => {}, subscribe: () => () => {} }';

function controlSource(id, { isUnique = 'omit' } = {}) {
  const uniqueLine = isUnique === false ? `\n  is_unique: false,` : '';
  return `import { defineBooleanControl } from "@theharborproject/trim";
export default defineBooleanControl({
  id: "${id}",
  label: "${id}",${uniqueLine}
  binding: ${NOOP_BOOLEAN_BINDING},
});
`;
}

/** A project with trim.json + a manifest/settings pair already agreeing with `controlIds`, and a given trim.config.tsx source — everything attach needs, without going through init/new-control's own interactive flows. */
function attachFixture(name, { controlIds = [], uniqueness = {}, configSource = DEFAULT_CONFIG } = {}) {
  const dir = path.join(testRoot, name);
  mkdirSync(path.join(dir, 'trim/controls'), { recursive: true });
  writeFileSync(path.join(dir, 'tsconfig.json'), JSON.stringify({ compilerOptions: { moduleResolution: 'bundler' } }), 'utf8');
  writeFileSync(path.join(dir, 'trim/trim.json'), serializeTrimMetadata({ version: 1, shadcn: false, styling: 'default' }), 'utf8');
  writeFileSync(path.join(dir, 'trim/trim.config.tsx'), configSource, 'utf8');
  for (const id of controlIds) {
    writeFileSync(path.join(dir, `trim/controls/${id}.trim.ts`), controlSource(id, { isUnique: uniqueness[id] ?? 'omit' }), 'utf8');
  }
  writeFileSync(
    path.join(dir, 'trim/trim.manifest.ts'),
    controlIds.length === 0
      ? 'export const trimControls = [] as const;\n'
      : controlIds.map((id) => `import ${id} from "./controls/${id}.trim";`).join('\n') + `\n\nexport const trimControls = [\n${controlIds.map((id) => `  ${id},`).join('\n')}\n] as const;\n`,
    'utf8',
  );
  writeFileSync(path.join(dir, 'trim/trim.settings.ts'), generateSettingsFileContents([]), 'utf8');
  return dir;
}

function scriptedAsk(answers) {
  const queue = [...answers];
  return async (promptText) => {
    if (queue.length === 0) throw new Error(`scriptedAsk: ran out of answers (last prompt: ${JSON.stringify(promptText)})`);
    return queue.shift();
  };
}

const swallowLogs = async (fn) => {
  const original = console.log;
  const lines = [];
  console.log = (...args) => lines.push(args.join(' '));
  try { await fn(); } finally { console.log = original; }
  return lines.join('\n');
};

try {
  // --- attach into an existing group, append ordering ---
  {
    const dir = attachFixture('append-existing', {
      controlIds: ['theme', 'contrast'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    await swallowLogs(() => runAttachCommand(dir, 'contrast', scriptedAsk(['1', '1'])));
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.match(config, /controls: \["theme", "contrast"\]|controls: \[\s*"theme",\s*"contrast",?\s*\]/s);
    const order = [...config.matchAll(/"(theme|contrast)"/g)].map((m) => m[1]);
    assert.deepEqual(order, ['theme', 'contrast'], 'appended after the existing item, not before');
  }

  // --- before positioning ---
  {
    const dir = attachFixture('before-positioning', {
      controlIds: ['theme', 'contrast'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    // Attach to vision (1) -> Before (2) -> which control? theme is #1
    await swallowLogs(() => runAttachCommand(dir, 'contrast', scriptedAsk(['1', '2', '1'])));
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    const order = [...config.matchAll(/"(theme|contrast)"/g)].map((m) => m[1]);
    assert.deepEqual(order, ['contrast', 'theme'], 'placed before the target control');
  }

  // --- after positioning ---
  {
    const dir = attachFixture('after-positioning', {
      controlIds: ['theme', 'contrast', 'animations'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme", "contrast"] },\n  ]'),
    });
    // Attach to vision (1) -> After (3) -> which control? theme is #1
    await swallowLogs(() => runAttachCommand(dir, 'animations', scriptedAsk(['1', '3', '1'])));
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    const order = [...config.matchAll(/"(theme|contrast|animations)"/g)].map((m) => m[1]);
    assert.deepEqual(order, ['theme', 'animations', 'contrast'], 'placed immediately after the target control');
  }

  // --- create new group; empty groups array is the base case ---
  {
    const dir = attachFixture('create-new-group', { controlIds: ['theme'] });
    // "Attach to:" has no default (see attach-prompts.ts) — with zero
    // existing groups, "1" (+ Create new group) is still an explicit choice.
    await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', 'vision', ''])));
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.match(config, /id: "vision"/);
    assert.match(config, /label: "Vision"/);
    assert.match(config, /controls: \[\s*"theme",\s*\]/s);
  }

  // --- REGRESSION: invalid non-empty answers reprompt at every attach menu, ---
  // --- never silently fall back to "create new group" / first item / append ---
  {
    const dir = attachFixture('reprompt-on-invalid', {
      controlIds: ['existing', 'theme'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["existing"] },\n  ]'),
    });
    const output = await swallowLogs(() =>
      // Attach to: invalid(9), invalid(abc), then "1" (vision — the only group; "2" is + Create new group).
      // Position: invalid(9), then blank -> the documented Append default IS accepted here.
      runAttachCommand(dir, 'theme', scriptedAsk(['9', 'abc', '1', '9', ''])),
    );
    assert.match(output, /Please enter a number from 1 to 2\./, '"Attach to:" menu (no default) reprompts on out-of-range input');
    assert.match(output, /Please enter a number from 1 to 3, or press Enter for the default\./, '"Position:" menu keeps its documented default but still reprompts on invalid input');
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.match(config, /controls: \[\s*"existing",\s*"theme",?\s*\]/s, 'the attach eventually succeeded once valid input was given (appended, per the accepted blank default)');
  }
  {
    // "Which control?" (before/after target) has no default either.
    const dir = attachFixture('reprompt-target-choice', {
      controlIds: ['theme', 'contrast'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    // Attach to vision (1) -> Before (2) -> which control?: invalid(9), invalid(blank), then "1" (theme).
    const output = await swallowLogs(() => runAttachCommand(dir, 'contrast', scriptedAsk(['1', '2', '9', '', '1'])));
    assert.match(output, /Please enter a number from 1 to 1\./, '"Which control?" menu (no default) reprompts on out-of-range and blank input');
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    const order = [...config.matchAll(/"(theme|contrast)"/g)].map((m) => m[1]);
    assert.deepEqual(order, ['contrast', 'theme'], 'still correctly placed before the target once a valid choice was given');
  }

  // --- duplicate unique control rejected: fails before prompting, writes nothing ---
  {
    const dir = attachFixture('duplicate-unique', {
      controlIds: ['theme'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    const before = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    let asked = false;
    await assert.rejects(
      runAttachCommand(dir, 'theme', async () => { asked = true; return ''; }),
      UsageError,
    );
    assert.equal(asked, false, 'a unique control already attached is rejected before prompting');
    assert.equal(readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8'), before, 'config is untouched');
  }

  // --- is_unique: false allows repeated attachment, in string form AND object form ---
  {
    const dir = attachFixture('repeated-allowed', {
      controlIds: ['animations'],
      uniqueness: { animations: false },
      configSource: DEFAULT_CONFIG.replace(
        'groups: []',
        'groups: [\n    { id: "vision", label: "Vision", controls: ["animations"] },\n    { id: "motion", label: "Motion", controls: [] },\n  ]',
      ),
    });
    // Attach to "motion" (2nd group), append
    const output = await swallowLogs(() => runAttachCommand(dir, 'animations', scriptedAsk(['2', '1'])));
    assert.match(output, /now appears in 2 location/);
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.equal((config.match(/"animations"/g) ?? []).length, 2);
  }
  {
    // object-form existing attachment ({ id: "contrast", component: X }) is ALSO detected for uniqueness/counting
    const dir = attachFixture('object-form-detected', {
      controlIds: ['contrast'],
      uniqueness: { contrast: false },
      configSource: DEFAULT_CONFIG.replace(
        'groups: []',
        'groups: [\n    { id: "vision", label: "Vision", controls: [{ id: "contrast", component: CustomContrast }] },\n    { id: "motion", label: "Motion", controls: [] },\n  ]',
      ),
    });
    const output = await swallowLogs(() => runAttachCommand(dir, 'contrast', scriptedAsk(['2', '1'])));
    assert.match(output, /now appears in 2 location/, 'the object-form attachment was counted');
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.match(config, /\{ id: "contrast", component: CustomContrast \}/, 'the existing object-form item is preserved exactly, never simplified');
    assert.match(config, /controls: \[\s*"contrast",\s*\]/s, 'the NEW attachment defaults to the bare id, never cloning the override');
  }
  {
    // a unique control already attached in OBJECT form is still detected and rejected
    const dir = attachFixture('object-form-unique-rejected', {
      controlIds: ['contrast'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: [{ id: "contrast", component: CustomContrast }] },\n  ]'),
    });
    await assert.rejects(runAttachCommand(dir, 'contrast', async () => ''), UsageError);
  }

  // --- dotted refs, comments, custom imports, custom layout: all preserved byte-identical outside the edited region ---
  {
    const customConfig = `import { defineTrimConfig } from "@theharborproject/trim/react";
import { MyLayout } from "./layout";
// important comment

export default defineTrimConfig({
  layout: MyLayout,

  groups: [
    {
      id: "vision",
      label: "Vision",
      controls: [
        "loader.spinnerToggle",
        { id: "contrast", component: CustomContrast },
      ],
    },
  ],
});

// trailing host comment
`;
    const dir = attachFixture('preserve-host-content', { controlIds: ['theme', 'contrast'], configSource: customConfig });
    await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', '1'])));
    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.ok(config.startsWith('import { defineTrimConfig } from "@theharborproject/trim/react";\nimport { MyLayout } from "./layout";\n// important comment\n'), 'imports and comment byte-identical at the top');
    assert.match(config, /layout: MyLayout,/, 'custom layout expression preserved');
    assert.match(config, /"loader\.spinnerToggle",/, 'legacy dotted ref preserved, not reinterpreted as a manifest control id');
    assert.match(config, /\{ id: "contrast", component: CustomContrast \}/, 'existing object-form override preserved');
    assert.ok(config.trimEnd().endsWith('// trailing host comment'), 'trailing host comment preserved');
    assert.match(config, /"theme",/, 'the new attachment was added');
  }

  // --- unsupported dynamic `groups` expression fails safely, writes nothing ---
  {
    const dynamicConfig = `import { defineTrimConfig } from "@theharborproject/trim/react";
const groups = getGroups();
export default defineTrimConfig({ layout: "sections", groups });
`;
    const dir = attachFixture('dynamic-groups', { controlIds: ['theme'], configSource: dynamicConfig });
    await assert.rejects(runAttachCommand(dir, 'theme', async () => ''), UsageError);
    assert.equal(readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8'), dynamicConfig, 'untouched');
  }
  {
    // a groups ARRAY that's literal, but with an entry that isn't a plain object/string, is equally unsupported
    const weirdConfig = DEFAULT_CONFIG.replace('groups: []', 'groups: [{ id: "vision", label: "Vision", controls: [someVariable] }]');
    const dir = attachFixture('unsupported-item', { controlIds: ['theme'], configSource: weirdConfig });
    await assert.rejects(runAttachCommand(dir, 'theme', async () => ''), UsageError);
    assert.equal(readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8'), weirdConfig);
  }

  // --- missing config fails safely ---
  {
    const dir = attachFixture('missing-config', { controlIds: ['theme'] });
    rmSync(path.join(dir, 'trim/trim.config.tsx'));
    await assert.rejects(runAttachCommand(dir, 'theme', async () => ''), UsageError);
  }

  // --- missing control fails safely, suggests `trim new control` ---
  {
    const dir = attachFixture('missing-control');
    await assert.rejects(runAttachCommand(dir, 'nonexistent', async () => ''), /new control nonexistent/);
  }

  // --- not initialized (no trim.json) fails safely ---
  {
    const dir = path.join(testRoot, 'not-initialized');
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, 'tsconfig.json'), '{}', 'utf8');
    await assert.rejects(runAttachCommand(dir, 'theme', async () => ''), UsageError);
  }

  // --- invalid group id ---
  {
    const dir = attachFixture('invalid-group-id', { controlIds: ['theme'] });
    await assert.rejects(runAttachCommand(dir, 'theme', scriptedAsk(['1', 'Not Valid', ''])), UsageError);
  }

  // --- requested before/after target missing (direct plan-builder call, bypassing the numbered-choice UI) ---
  {
    const dir = attachFixture('target-missing', {
      controlIds: ['theme', 'contrast'], // "theme" is already attached (fine — the group still exists to position against); "contrast" is the one we're gathering info for, not yet attached anywhere
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    const info = await gatherAttachInfo(dir, 'contrast');
    assert.throws(() => buildAttachEdit(info, { mode: 'existing-group', groupId: 'vision', position: { before: 'does-not-exist' } }), UsageError);
  }

  // --- host with NO `typescript` installed at all still works: attach never touches the host's TypeScript, only Trim's own bundled compiler ---
  {
    const dir = path.join('/tmp', `trim-attach-no-ts-${process.pid}`);
    mkdirSync(path.join(dir, 'trim/controls'), { recursive: true });
    writeFileSync(path.join(dir, 'tsconfig.json'), '{}', 'utf8');
    writeFileSync(path.join(dir, 'trim/trim.json'), serializeTrimMetadata({ version: 1, shadcn: false, styling: 'default' }), 'utf8');
    writeFileSync(path.join(dir, 'trim/trim.config.tsx'), DEFAULT_CONFIG, 'utf8');
    writeFileSync(path.join(dir, 'trim/controls/theme.trim.ts'), controlSource('theme'), 'utf8');
    try {
      await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', 'vision', ''])));
      const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
      assert.match(config, /id: "vision"/);
      assert.match(config, /controls: \[\s*"theme",\s*\]/s);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }

  // --- transactional: no writes on any validation failure (duplicate-unique case, checked precisely) ---
  {
    const dir = attachFixture('no-writes-on-failure', {
      controlIds: ['theme'],
      configSource: DEFAULT_CONFIG.replace('groups: []', 'groups: [\n    { id: "vision", label: "Vision", controls: ["theme"] },\n  ]'),
    });
    const beforeConfig = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    const beforeManifest = readFileSync(path.join(dir, 'trim/trim.manifest.ts'), 'utf8');
    const beforeSettings = readFileSync(path.join(dir, 'trim/trim.settings.ts'), 'utf8');
    const beforeControl = readFileSync(path.join(dir, 'trim/controls/theme.trim.ts'), 'utf8');
    await assert.rejects(runAttachCommand(dir, 'theme', async () => ''), UsageError);
    assert.equal(readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8'), beforeConfig);
    assert.equal(readFileSync(path.join(dir, 'trim/trim.manifest.ts'), 'utf8'), beforeManifest, 'manifest byte-identical');
    assert.equal(readFileSync(path.join(dir, 'trim/trim.settings.ts'), 'utf8'), beforeSettings, 'settings byte-identical');
    assert.equal(readFileSync(path.join(dir, 'trim/controls/theme.trim.ts'), 'utf8'), beforeControl, 'control declaration byte-identical');
  }

  // --- a SUCCESSFUL attach still leaves manifest/settings/declaration byte-identical — only config.tsx changes ---
  {
    const dir = attachFixture('only-config-changes', { controlIds: ['theme'] });
    const beforeManifest = readFileSync(path.join(dir, 'trim/trim.manifest.ts'), 'utf8');
    const beforeSettings = readFileSync(path.join(dir, 'trim/trim.settings.ts'), 'utf8');
    const beforeControl = readFileSync(path.join(dir, 'trim/controls/theme.trim.ts'), 'utf8');
    await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', 'vision', ''])));
    assert.equal(readFileSync(path.join(dir, 'trim/trim.manifest.ts'), 'utf8'), beforeManifest);
    assert.equal(readFileSync(path.join(dir, 'trim/trim.settings.ts'), 'utf8'), beforeSettings);
    assert.equal(readFileSync(path.join(dir, 'trim/controls/theme.trim.ts'), 'utf8'), beforeControl);
  }

  // --- config still typechecks after the edit ---
  {
    const dir = attachFixture('typecheck-after-edit', { controlIds: ['theme', 'contrast'] });
    await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', 'vision', ''])));
    await swallowLogs(() => runAttachCommand(dir, 'contrast', scriptedAsk(['1', '1'])));
    const files = ['trim/controls/theme.trim.ts', 'trim/controls/contrast.trim.ts', 'trim/trim.manifest.ts', 'trim/trim.settings.ts', 'trim/trim.config.tsx'].map((p) => path.relative(root, path.join(dir, p)));
    execFileSync('node', [
      'node_modules/typescript/bin/tsc', ...files,
      '--noEmit', '--strict', '--module', 'esnext', '--moduleResolution', 'bundler', '--target', 'es2020', '--jsx', 'react-jsx', '--skipLibCheck',
    ], { cwd: root });
  }

  // --- a REAL end-to-end fixture sequence, exactly as specified for this step ---
  {
    const { runInitCommand } = require(path.join(root, 'dist/cli/commands/init.js'));
    const { runNewControlCommand } = require(path.join(root, 'dist/cli/commands/new-control.js'));
    const dir = path.join(testRoot, 'real-sequence');
    mkdirSync(dir, { recursive: true });
    writeFileSync(path.join(dir, 'tsconfig.json'), JSON.stringify({ compilerOptions: { moduleResolution: 'bundler' } }), 'utf8');

    await swallowLogs(() => runInitCommand(dir, async () => ({ useShadcn: false, styling: 'default' })));
    await swallowLogs(() => runNewControlCommand(dir, 'theme', scriptedAsk(['2', '', 'n', 'light', '', 'dark', '', '', '1', '1'])));
    await swallowLogs(() => runAttachCommand(dir, 'theme', scriptedAsk(['1', 'vision', ''])));

    await swallowLogs(() => runNewControlCommand(dir, 'animations', scriptedAsk(['1', '', 'y', '1', 'y'])));
    await swallowLogs(() => runAttachCommand(dir, 'animations', scriptedAsk(['1', '1']))); // vision, append
    await swallowLogs(() => runAttachCommand(dir, 'animations', scriptedAsk(['2', 'motion', '']))); // new group "motion"
    let thirdAttachFailed = false;
    try {
      await swallowLogs(() => runAttachCommand(dir, 'animations', scriptedAsk(['1', '1'])));
    } catch {
      thirdAttachFailed = true; // is_unique:false — a THIRD attach must NOT fail
    }

    const config = readFileSync(path.join(dir, 'trim/trim.config.tsx'), 'utf8');
    assert.equal((config.match(/"animations"/g) ?? []).length, 3, 'animations attached three times total, all allowed (is_unique: false)');
    assert.match(config, /"theme"/);
    assert.equal(thirdAttachFailed, false);

    const files = ['trim/controls/theme.trim.ts', 'trim/controls/animations.trim.ts', 'trim/trim.manifest.ts', 'trim/trim.settings.ts', 'trim/trim.config.tsx'].map((p) => path.relative(root, path.join(dir, p)));
    execFileSync('node', ['node_modules/typescript/bin/tsc', ...files, '--noEmit', '--strict', '--module', 'esnext', '--moduleResolution', 'bundler', '--target', 'es2020', '--jsx', 'react-jsx', '--skipLibCheck'], { cwd: root });
  }

  // --- tarball: attach's CLI files ship, no test fixtures leak in ---
  {
    const json = execFileSync('npm', ['pack', '--dry-run', '--ignore-scripts', '--json'], { cwd: root, encoding: 'utf8' });
    const files = JSON.parse(json)[pkg.name].files.map((f) => f.path);
    for (const f of ['dist/cli/commands/attach.js', 'dist/cli/generators/attach-plan.js', 'dist/cli/project/trim-config-ast.js', 'dist/cli/project/control-uniqueness.js', 'dist/cli/project/resolve-typescript.js', 'dist/cli/prompts/attach-prompts.js', 'dist/cli/prompts/prompt-utils.js']) {
      assert.ok(files.includes(f), `${f} should ship in dist/cli`);
    }
    assert.ok(!files.some((f) => f.startsWith('.trim-cli-attach-test-')), 'no test fixture directory leaks into the tarball');
  }

  console.log('PASS CLI attach: append/before/after positioning, create new group (incl. empty groups array), reprompt (not silent fallback) on invalid input at the "Attach to:"/"Position:"/"Which control?" menus, duplicate-unique rejected before prompting, is_unique:false repeated attachment (string form AND object form both detected/counted, new attachment never clones an existing override), dotted refs + comments + custom imports + custom layout all preserved byte-identical, unsupported dynamic groups/entry shapes fail safely with nothing written, missing config/control/trim.json fail clearly, invalid group id rejected, missing before/after target rejected, host with no `typescript` installed at all still attaches fine (Trim never touches host TypeScript, only its own bundled compiler), transactional (no writes on any failure, and a SUCCESSFUL attach touches only trim.config.tsx — manifest/settings/declaration stay byte-identical), config still typechecks after every edit, a real init->new control->attach(x3) sequence works end to end, tarball ships attach\'s CLI files without test fixtures');
} finally {
  rmSync(testRoot, { recursive: true, force: true });
}
