"use client";

// Generated by Trim (`trim init`, ui.adapter: "shadcn", ui.shell: "dialog").
// Host-owned from this point on — Trim's runtime has no idea this file
// exists or that shadcn is involved (ui.adapter !== "vanilla" always
// resolves to a zero-wrapper passthrough at runtime; see
// src/react/shell/resolve.ts): it only ever renders
// <Trim.Panel config={trimConfig} />. Uses your project's own shadcn
// Button + Dialog components (see components.json's "ui" alias) — remove
// or hand-edit freely, `trim init` never rewrites this file after creation.
import { Button } from "__TRIM_SHADCN_UI_IMPORT__/button";
import { Dialog, DialogContent, DialogTrigger } from "__TRIM_SHADCN_UI_IMPORT__/dialog";
import { Panel } from "@theharborproject/trim/react";
import trimConfig from "__TRIM_CONFIG_IMPORT__";

export function TrimShell() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Accessibility</Button>
      </DialogTrigger>
      <DialogContent>
        <Panel config={trimConfig} />
      </DialogContent>
    </Dialog>
  );
}
