// Trim CLI — trim/controls/<id>.trim.ts generation, using only public core
// APIs (define*Control factories, callback()). This file never imports
// src/** — the same public entry points a hand-written control file would
// use, matching examples/default's own canonical pattern.

import { relativeImportSpecifier, relativePathBetween } from "../project/module-resolution";
import type { ModuleResolutionMode } from "../project/detect-project";
import { controlIdToIdentifier } from "./manifest-file";

export type ControlKind = "boolean" | "segmented" | "action" | "toggle-action";

export type SegmentedOptionSpec = { value: string; label: string };

/**
 * "trim-managed" needs no options/values BinDIng-side (both the schema and
 * the exported binding live in trim.settings.ts) — this file only ever
 * imports `trimSettings.<id>` for that case. "existing" and "callback"
 * mirror the public TrimBinding-construction primitives directly: an
 * already-built TrimBinding the project exports, or callback(get, set,
 * subscribe?). `getSymbol` is optional only for a void-valued (Action)
 * callback binding, where there is no meaningful value to read back —
 * generated as `() => undefined` instead of an import.
 */
export type BindingSpec =
  | { mode: "trim-managed"; defaultValue: boolean | string }
  | { mode: "existing"; importPath: string; symbol: string }
  | { mode: "callback"; importPath: string; getSymbol?: string; setSymbol: string; subscribeSymbol?: string };

export type NewControlSpec = {
  id: string;
  kind: ControlKind;
  label: string;
  /** Maps to `is_unique: false` when true; the field is omitted entirely when false — undefined already means unique. */
  allowMultiple: boolean;
  /** Required (and only meaningful) when kind === "segmented". */
  options?: readonly SegmentedOptionSpec[];
  binding: BindingSpec;
};

const FACTORY_BY_KIND: Record<ControlKind, string> = {
  boolean: "defineBooleanControl",
  segmented: "defineSegmentedControl",
  action: "defineActionControl",
  "toggle-action": "defineToggleActionControl",
};

function bindingImportsAndExpression(spec: NewControlSpec, moduleResolution: ModuleResolutionMode): { imports: readonly string[]; expression: string } {
  const binding = spec.binding;
  if (binding.mode === "trim-managed") {
    return {
      imports: [`import { trimSettings } from "${relativeImportSpecifier(moduleResolution, "../trim.settings")}";`],
      expression: `trimSettings.${controlIdToIdentifier(spec.id)}`,
    };
  }
  // "existing" and "callback" both carry `importPath` relative to the
  // PROJECT ROOT (what the wizard asks for — the natural way a user thinks
  // about their own file tree), which must be converted to a path relative
  // to trim/controls/<id>.trim.ts's own location before it can appear as
  // an import specifier in the generated file.
  const controlFileNoExt = `trim/controls/${spec.id}.trim`;
  const relativeSpecifier = relativeImportSpecifier(moduleResolution, relativePathBetween(controlFileNoExt, binding.importPath));
  if (binding.mode === "existing") {
    return {
      imports: [`import { ${binding.symbol} } from "${relativeSpecifier}";`],
      expression: binding.symbol,
    };
  }
  const importedSymbols = [binding.getSymbol, binding.setSymbol, binding.subscribeSymbol].filter((s): s is string => Boolean(s));
  const getExpression = binding.getSymbol ?? "() => undefined";
  const callArgs = [getExpression, binding.setSymbol, binding.subscribeSymbol].filter(Boolean).join(", ");
  return {
    imports: [`import { callback } from "@theharborproject/trim";`, `import { ${importedSymbols.join(", ")} } from "${relativeSpecifier}";`],
    expression: `callback(${callArgs})`,
  };
}

export function generateControlFileContents(spec: NewControlSpec, moduleResolution: ModuleResolutionMode): string {
  const factory = FACTORY_BY_KIND[spec.kind];
  const { imports, expression } = bindingImportsAndExpression(spec, moduleResolution);

  const fields: string[] = [`  id: ${JSON.stringify(spec.id)},`, `  label: ${JSON.stringify(spec.label)},`];
  if (spec.allowMultiple) fields.push(`  is_unique: false,`);
  if (spec.kind === "segmented" && spec.options) {
    const optionsLiteral = spec.options.map((o) => `{ value: ${JSON.stringify(o.value)}, label: ${JSON.stringify(o.label)} }`).join(", ");
    fields.push(`  options: [${optionsLiteral}],`);
  }
  fields.push(`  binding: ${expression},`);

  const stateComment =
    spec.binding.mode === "trim-managed"
      ? "// Trim-managed state: `binding` comes from ../trim.settings.ts's host-owned controller (see that file — one shared controller for every Trim-managed control)."
      : "// Project-managed state: `binding` points at state this project already owns — Trim never duplicates or takes ownership of it.";

  return `// Generated by Trim. Host-owned — Trim itself never rewrites this file
// after creation; only \`trim new control\` creates it.
${stateComment}
import { ${factory} } from "@theharborproject/trim";
${imports.join("\n")}

export default ${factory}({
${fields.join("\n")}
});
`;
}
