// Trim CLI — `trim init`'s file generation, planning, and application.
// Split deliberately into three phases (see cli/commands/init.ts for how
// they compose): generate canonical contents (pure), diff against disk to
// build a plan (reads only), then apply the plan (writes only the safe
// part of it, and only when the WHOLE plan is safe — see FileStatus's own
// comment on "conflict"). No file this package doesn't own is ever touched.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ProjectInfo } from "../project/detect-project";
import { relativeImportSpecifier } from "../project/module-resolution";
import { TRIM_JSON_PATH, serializeTrimMetadata, type Styling, type TrimProjectMetadata } from "../project/trim-metadata";
import { generateSettingsFileContents } from "./settings-file";
import { generateManifestFileContents } from "./manifest-file";

export type { Styling };

export type InitAnswers = {
  useShadcn: boolean;
  styling: Styling;
};

/**
 * "create": doesn't exist yet. "matches": exists, byte-identical to what
 * we'd generate — nothing to do. "conflict": exists with different
 * content — never written, and its presence blocks the ENTIRE plan (see
 * cli/commands/init.ts: any conflict means nothing in the batch is
 * applied, not just that one file). "update": exists with different
 * content, but is always safe to overwrite — used only for trim/trim.json,
 * whose whole purpose is recording the CURRENT answers; re-running init
 * with a different answer is expected to update it, not "conflict" with
 * its previous self. An "update" entry does not, on its own, block the
 * plan — but the plan as a whole still only applies if there is no
 * "conflict" anywhere in it.
 */
export type FileStatus = "create" | "matches" | "conflict" | "update";

export type PlannedFile = {
  /** Project-relative, forward-slash path — safe to join with any cwd via path.join. */
  path: string;
  contents: string;
  status: FileStatus;
};

export type InitPlan = {
  files: readonly PlannedFile[];
  /** Human-readable context: shadcn caveats, styling instructions — never file contents. */
  notes: readonly string[];
  /** The exact snippet trim init prints for wiring <Trim.Registry>/<Trim.Panel>. */
  integrationSnippet: string;
};

export const CONFIG_PATH = "trim/trim.config.tsx";
export const MANIFEST_PATH = "trim/trim.manifest.ts";
export const SETTINGS_PATH = "trim/trim.settings.ts";
export const TOKENS_CSS_PATH = "trim/trim.css";
export { TRIM_JSON_PATH };

// --- content generators — pure, deterministic, independent of shadcn/styling ---
// (neither answer changes what these three files contain; see the header
// comment on generateTokensCssContents for the one file that does vary,
// and trim.json's own planning below for the other)

export function generateConfigContents(): string {
  return `// Generated by Trim. Host-owned — customize freely; the Trim CLI only
// edits this file's \`groups\` array structurally, via \`trim attach\`.
import { defineTrimConfig } from "@theharborproject/trim/react";

export default defineTrimConfig({
  layout: "sections",
  groups: [],
});
`;
}

/** The empty case of the same generator \`trim new control\` uses to regenerate this file with a real import list — see cli/generators/manifest-file.ts. moduleResolution is irrelevant for an empty import list, so any value works here. */
export function generateManifestContents(): string {
  return generateManifestFileContents([], "classic-or-bundler");
}

/** The empty case of the same generator \`trim new control\` uses to regenerate this file with a real schema — see cli/generators/settings-file.ts. */
export function generateSettingsContents(): string {
  return generateSettingsFileContents([]);
}

const PROJECT_TOKEN_TO_TRIM_TOKEN: Record<string, string> = {
  background: "bg",
  foreground: "ink",
  "muted-foreground": "muted",
  border: "line",
  radius: "radius",
};

/**
 * The one generated file whose CONTENT genuinely depends on what's on
 * disk: `identifiedTokens` come from detect-project.ts's scan of the
 * host's own global stylesheet. When nothing recognizable was found, this
 * never invents shadcn/Tailwind variable names — it generates concrete,
 * clearly-labeled starter values instead.
 */
export function generateTokensCssContents(identifiedTokens: readonly string[]): { contents: string; usedIdentifiedTokens: boolean } {
  if (identifiedTokens.length > 0) {
    const lines = identifiedTokens.map((name) => `  --trim-${PROJECT_TOKEN_TO_TRIM_TOKEN[name]}: var(--${name});`);
    return {
      usedIdentifiedTokens: true,
      contents: `/* Generated by Trim. Maps --trim-* tokens to project variables found in
   your global stylesheet. Load this AFTER
   @theharborproject/trim/themes/default.css so these values win the
   cascade — see that file for the complete token contract. */
[data-trim-panel] {
${lines.join("\n")}
}
`,
    };
  }
  return {
    usedIdentifiedTokens: false,
    contents: `/* Generated by Trim. No recognizable project design tokens (--background,
   --foreground, --border, --muted-foreground, --radius) were found, so
   these are standalone starter values — NOT references to your project's
   real tokens. Edit them, e.g. --trim-bg: var(--your-background-token).
   Load this AFTER @theharborproject/trim/themes/default.css so these
   values win the cascade. */
[data-trim-panel] {
  --trim-bg: #fff;
  --trim-ink: #111;
  --trim-line: #ccc;
}
`,
  };
}

function buildIntegrationSnippet(project: ProjectInfo): string {
  const configSpec = relativeImportSpecifier(project.moduleResolution, "./trim/trim.config");
  const manifestSpec = relativeImportSpecifier(project.moduleResolution, "./trim/trim.manifest");
  return `import { Trim } from "@theharborproject/trim/react";
import trimConfig from "${configSpec}";
import { trimControls } from "${manifestSpec}";

<Trim.Registry controls={trimControls}>
  <Trim.Panel config={trimConfig} />
</Trim.Registry>`;
}

function cssImportInstruction(project: ProjectInfo, specifiers: readonly string[]): string {
  const lines = [
    "Add this to wherever your project loads global styles (a CSS file, or a JS/TS entry point):",
    ...specifiers.map((s) => `  import "${s}";`),
    `  (or, from plain CSS: ${specifiers.map((s) => `@import "${s}";`).join(" ")})`,
  ];
  if (project.globalStylesheet) {
    lines.push(`We found ${project.globalStylesheet} as a likely global stylesheet, but did not edit it — add the import there yourself, or wherever fits your project.`);
  }
  return lines.join("\n");
}

async function readIfExists(cwd: string, relativePath: string): Promise<string | undefined> {
  try {
    return await readFile(path.join(cwd, relativePath), "utf8");
  } catch {
    return undefined;
  }
}

function planFile(relativePath: string, contents: string, existing: string | undefined): PlannedFile {
  if (existing === undefined) return { path: relativePath, contents, status: "create" };
  return { path: relativePath, contents, status: existing === contents ? "matches" : "conflict" };
}

/** trim.json is never a "conflict": its whole purpose is recording the current answers, so a rerun with different answers should update it, not block on it. */
function planMetadataFile(relativePath: string, contents: string, existing: string | undefined): PlannedFile {
  if (existing === undefined) return { path: relativePath, contents, status: "create" };
  return { path: relativePath, contents, status: existing === contents ? "matches" : "update" };
}

/**
 * Reads only — never writes. `answers` only changes: (1) whether a shadcn
 * caveat note is added and what trim.json records, (2) whether
 * trim/trim.css is planned at all and what it contains, (3) the wording of
 * the CSS-import note. The three core generated-code files
 * (config/manifest/settings) are identical regardless of `answers`, by
 * design — see their generators' own comments.
 */
export async function buildInitPlan(project: ProjectInfo, answers: InitAnswers): Promise<InitPlan> {
  const notes: string[] = [];
  const files: PlannedFile[] = [
    planFile(CONFIG_PATH, generateConfigContents(), await readIfExists(project.cwd, CONFIG_PATH)),
    planFile(MANIFEST_PATH, generateManifestContents(), await readIfExists(project.cwd, MANIFEST_PATH)),
    planFile(SETTINGS_PATH, generateSettingsContents(), await readIfExists(project.cwd, SETTINGS_PATH)),
  ];

  // "require the prerequisite before accepting Yes" is enforced primarily
  // at the prompt layer (cli/prompts/init-prompts.ts skips the question
  // entirely when shadcn isn't configured) — this is the defense-in-depth
  // copy for any caller (a test, a future non-interactive mode) that
  // passes useShadcn: true directly: trim.json never records `true` unless
  // shadcnConfigured independently confirms it, regardless of what was
  // asked for.
  const effectiveShadcn = answers.useShadcn && project.shadcnConfigured;
  if (answers.useShadcn && !project.shadcnConfigured) {
    notes.push(
      'You chose "Use shadcn components", but no components.json was found — shadcn does not appear to be set up in this project. ' +
        "Install/configure it first (https://ui.shadcn.com/docs/installation), then re-run `trim init` to enable it. " +
        "trim/trim.json records shadcn: false for now — no shadcn-specific files are generated by `init` either way.",
    );
  } else if (answers.useShadcn) {
    notes.push("shadcn preference recorded in trim/trim.json for later `trim new control` / `trim add` commands — `init` itself generates nothing shadcn-specific.");
  }
  if (effectiveShadcn) {
    // A note only, never an automatic install — see cli/generators/
    // shadcn-registry.ts's own header: an explicit "@shadcn/..." ref is
    // still required, and it re-verifies the real shadcn setup itself
    // rather than trusting this recorded preference.
    notes.push("Shadcn templates are available, e.g. `trim add @shadcn/controls/boolean`.");
  }

  const metadata: TrimProjectMetadata = { version: 1, shadcn: effectiveShadcn, styling: answers.styling };
  files.push(planMetadataFile(TRIM_JSON_PATH, serializeTrimMetadata(metadata), await readIfExists(project.cwd, TRIM_JSON_PATH)));

  const defaultThemeImport = "@theharborproject/trim/themes/default.css";
  if (answers.styling === "default") {
    notes.push(cssImportInstruction(project, [defaultThemeImport]));
  } else if (answers.styling === "tokens") {
    const { contents, usedIdentifiedTokens } = generateTokensCssContents(project.identifiedProjectTokens);
    files.push(planFile(TOKENS_CSS_PATH, contents, await readIfExists(project.cwd, TOKENS_CSS_PATH)));
    notes.push(
      usedIdentifiedTokens
        ? `Mapped ${project.identifiedProjectTokens.length} token(s) found in ${project.globalStylesheet} into ${TOKENS_CSS_PATH}.`
        : `No recognizable project design tokens were found${project.globalStylesheet ? ` in ${project.globalStylesheet}` : ""} — generated ${TOKENS_CSS_PATH} with standalone starter values instead of guessed token names. Edit it to reference your own tokens.`,
    );
    notes.push(cssImportInstruction(project, [defaultThemeImport, `./${TOKENS_CSS_PATH}`]));
  } else {
    notes.push("Fully headless — no Trim CSS import needed. Style [data-trim-panel]/[data-trim-control]/etc. yourself using Trim's data-attribute contract.");
  }

  return { files, notes, integrationSnippet: buildIntegrationSnippet(project) };
}

/**
 * Writes "create" and "update" entries; "matches" needs no write;
 * "conflict" is never overwritten. Callers (cli/commands/init.ts) are
 * expected to check for "conflict" BEFORE calling this at all — plan
 * application is all-or-nothing at the command level, not per file — but
 * this still individually skips any conflict entry as a defensive
 * safeguard, never as the primary transactional guarantee.
 */
export async function applyInitPlan(cwd: string, plan: InitPlan): Promise<void> {
  for (const file of plan.files) {
    if (file.status !== "create" && file.status !== "update") continue;
    const fullPath = path.join(cwd, file.path);
    await mkdir(path.dirname(fullPath), { recursive: true });
    await writeFile(fullPath, file.contents, "utf8");
  }
}
