// Trim CLI — trim/trim.manifest.ts generation. The ONE place that knows
// what this file looks like, for both `trim init` (writes the empty
// placeholder) and `trim new control` (regenerates it with a real import
// list).
//
// trim.manifest.ts's content is a pure function of "which control ids
// exist" — never parsed back from its own previous content: `trim new
// control` derives the current control list directly from
// trim/controls/*.trim.ts on disk (a plain directory listing at CLI-time,
// not runtime discovery — the RESULT is what gets written here as static
// imports). That sidesteps ever needing to parse this file's own import
// syntax back out of it.

import { relativeImportSpecifier } from "../project/module-resolution";
import type { ModuleResolutionMode } from "../project/detect-project";

/** "reduced-motion" -> "reducedMotion": kebab-case ids need a valid JS identifier for the import binding. */
export function controlIdToIdentifier(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_match, char: string) => char.toUpperCase());
}

/**
 * Lexical id order, not creation order: regeneration is then deterministic
 * regardless of which control was added in which command invocation —
 * the same choice, and the same reasoning, as
 * cli/generators/settings-file.ts's schema entries.
 */
export function generateManifestFileContents(controlIds: readonly string[], moduleResolution: ModuleResolutionMode): string {
  const sorted = [...controlIds].sort((a, b) => a.localeCompare(b));

  if (sorted.length === 0) {
    return `// Generated by Trim. Updated by the Trim CLI — do not hand-edit;
// \`trim new control\` appends to this file automatically.
export const trimControls = [] as const;
`;
  }

  const imports = sorted.map((id) => `import ${controlIdToIdentifier(id)} from "${relativeImportSpecifier(moduleResolution, `./controls/${id}.trim`)}";`);
  const entries = sorted.map((id) => `  ${controlIdToIdentifier(id)},`);

  return `// Generated by Trim. Updated by the Trim CLI — do not hand-edit;
// \`trim new control\` appends to this file automatically. Entries are kept
// in lexical id order, so regeneration is deterministic regardless of the
// order controls were added in.
${imports.join("\n")}

export const trimControls = [
${entries.join("\n")}
] as const;
`;
}
